name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
#, macos-latest]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            cxx_compiler_install: "sudo apt update; sudo apt install gcc-11 g++-11"
            cxx_compiler: g++-11
          #- os: macos-latest
            #cxx_compiler: g++-11
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - if: ${{ matrix.cxx_compiler_install }}
      name: Install C++ compiler
      run: ${{ matrix.cxx_compiler_install }}

    - name: Download LibTorch
      run: |
        wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.10.1%2Bcpu.zip
        unzip libtorch-cxx11-abi-shared-with-deps-1.10.1+cpu.zip

    - name: Configure CMake
      env:
        CXX: ${{ matrix.cxx_compiler }}
      run: 
        cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_PREFIX_PATH=${{github.workspace}}/libtorch/ 
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: cmake --build ${{github.workspace}}/build --target test
    
